[main]
host="0.0.0.0:8082"
log_level="trace"
# 运行模式 demo/debug/prod
mode="demo"
time_zone="Asia/Shanghai"

[db]
# driver = "postgres" 
# dsn = "host=localhost port=15432 user=postgres password=postgres dbname=test sslmode=disable"

driver="mysql"
dsn = "root:root@tcp(localhost:13306)/test?charset=utf8&loc=Local"
show_sql = true


[redis]
host = "127.0.0.1:16379"
db = 0
password = ""

# 成交记录给结算系统
trade_record="trade_record:{symbol}"
# trade_log_subscribe_key="list:trade_log"






[kline]
interval=["m1", "d1", "mn"]



[test]
user1=101
user2=102
trade_symbol = "ethusd"
symbol = "eth"
standard= "usd"
initAmount = 10000



