// This file is generated by GoAdmin CLI adm.
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "assets" => http://localhost:9033/admin/info/assets
// "exchange_option" => http://localhost:9033/admin/info/exchange_option
//
// example end
var Generators = map[string]table.Generator{

	"assets":          GetAssetsTable,
	"exchange_option": GetExchangeOptionTable,

	// generators end
}
