// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/assets/query": {
            "get": {
                "description": "获取交易规则、交易对信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "用户资产查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "资产symbols用逗号分隔 eg: eth,usd",
                        "name": "symbols",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/depth": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "深度信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "eg: ethusd",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "默认100，最大5000",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/exchange/info": {
            "get": {
                "description": "获取交易规则、交易对信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "交易对信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "交易对symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/market/klines": {
            "get": {
                "description": "行情k线数据接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "行情接口"
                ],
                "summary": "行情k线数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "eg: ethusd",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "m1,m3,m5...",
                        "name": "period",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "default: 10",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Kline"
                        }
                    }
                }
            }
        },
        "/api/v1/order": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orders.TradeOrder"
                        }
                    }
                }
            }
        },
        "/api/v1/order/all": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/order/cancel": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取消还未完成的订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单相关"
                ],
                "summary": "取消委托",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.cancel_order_request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/order/new": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新订单，支持限价单、市价单\n不同订单类型的参数要求：\n限价单: {\"symbol\": \"ethusd\", \"order_type\": \"limit\", \"side\": \"sell/buy\", \"price\": \"1.00\", \"quantity\": \"100\"}\n市价-按数量: {\"symbol\": \"ethusd\", \"order_type\": \"market\", \"side\": \"sell/buy\", \"quantity\": \"100\"}\n市价-按金额: {\"symbol\": \"ethusd\", \"order_type\": \"market\", \"side\": \"sell/buy\", \"amount\": \"1000.00\"}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单相关"
                ],
                "summary": "委托订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.new_order_request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/order/open": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/trade/record": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "成交记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "eg: ethusd",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "默认10，最大100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/orders.TradeRecord"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.cancel_order_request": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                }
            }
        },
        "api.new_order_request": {
            "type": "object",
            "required": [
                "order_type",
                "side",
                "symbol"
            ],
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "100.00"
                },
                "order_type": {
                    "type": "string",
                    "example": "limit/market"
                },
                "price": {
                    "type": "string",
                    "example": "1.00"
                },
                "quantity": {
                    "type": "string",
                    "example": "12"
                },
                "side": {
                    "type": "string",
                    "example": "sell/buy"
                },
                "symbol": {
                    "type": "string",
                    "example": "ethusd"
                }
            }
        },
        "common.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "ok": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "models.Kline": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "成交额",
                    "type": "string"
                },
                "close": {
                    "description": "收盘价(当前K线未结束的即为最新价)",
                    "type": "string"
                },
                "close_at": {
                    "description": "收盘时间",
                    "type": "string"
                },
                "high": {
                    "description": "最高价",
                    "type": "string"
                },
                "low": {
                    "description": "最低价",
                    "type": "string"
                },
                "open": {
                    "description": "开盘价",
                    "type": "string"
                },
                "open_at": {
                    "description": "开盘时间",
                    "type": "string"
                },
                "trade_count": {
                    "description": "成交笔数",
                    "type": "integer"
                },
                "volume": {
                    "description": "成交量",
                    "type": "string"
                }
            }
        },
        "orders.TradeOrder": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "时间戳 精确到纳秒",
                    "type": "integer"
                },
                "finished_qty": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "order_side": {
                    "type": "string"
                },
                "order_type": {
                    "description": "价格策略，市价单，限价单",
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "trade_amount": {
                    "type": "string"
                }
            }
        },
        "orders.TradeRecord": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "ask": {
                    "type": "string"
                },
                "bid": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "trade_at": {
                    "type": "string"
                },
                "trade_by": {
                    "type": "integer"
                },
                "trade_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
